name: Publish dev to GitHub Pages

on:
  push:
    branches:
      - "main"

concurrency:
  group: pages-main
  cancel-in-progress: true

env:
  "GODOT_VERSION": "4.7-stable"

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Download Godot
        run: |
          wget https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_linux.x86_64.zip

          unzip Godot_v${GODOT_VERSION}_linux.x86_64.zip

      - name: Cache Godot export templates
        uses: actions/cache@v4
        id: cache-templates
        with:
          path: ~/.local/share/godot/export_templates
          key: godot-export-templates-${{ env.GODOT_VERSION }}

      - name: Download Export Templates
        if: steps.cache-templates.outputs.cache-hit != 'true'
        run: |
          GODOT_TEMPLATE_VERSION=${GODOT_VERSION/-/.}
          wget https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_export_templates.tpz

          mkdir -p ~/.local/share/godot/export_templates/${GODOT_TEMPLATE_VERSION}

          unzip Godot_v${GODOT_VERSION}_export_templates.tpz -d /tmp/godot_templates
          mv /tmp/godot_templates/templates/* ~/.local/share/godot/export_templates/${GODOT_TEMPLATE_VERSION}

      - name: Find Godot executable
        run: |
          GODOT_BIN=$(find . -type f -name "Godot_v${GODOT_VERSION}_linux.x86_64" | head -n1)
          chmod +x "$GODOT_BIN"
          echo "GODOT_BIN=$GODOT_BIN" >> $GITHUB_ENV
      
      - name: Import Project
        run: |
          "$GODOT_BIN" --headless --path src --import

      - name: Export Web
        run: |
          mkdir -p build/web

          "$GODOT_BIN" --headless --path src --export-release "Web" "$GITHUB_WORKSPACE/build/web/index.html"
      
      - name: Add coi-service-worker
        run: |
          git clone https://github.com/gzuidhof/coi-serviceworker.git
          mv coi-serviceworker/coi-serviceworker.js build/web/coi-serviceworker.js
          sed -i '3 i <script src="coi-serviceworker.js"></script>' build/web/index.html

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
          destination_dir: latest
          user_name: "github-ci[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Publish to gh-pages"
