name: Publish to itch.io

on:
  push:
    tags:
      - 'v*'

env:
  "GODOT_VERSION": "4.7-stable"

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Butler
        run: |
          wget https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default -O butler.zip

          unzip butler.zip
          chmod +x butler

      - name: Cache Godot
        id: cache-godot
        uses: actions/cache@v4
        with:
          path: Godot_v${{ env.GODOT_VERSION }}_linux.x86_64.zip
          key: godot-${{ env.GODOT_VERSION }}-linux

      - name: Download Godot
        if: steps.cache-godot.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_linux.x86_64.zip
          unzip Godot_v${GODOT_VERSION}_linux.x86_64.zip

      - name: Cache Godot export templates
        uses: actions/cache@v4
        id: cache-templates
        with:
          path: ~/.local/share/godot/export_templates
          key: godot-export-templates-${{ env.GODOT_VERSION }}

      - name: Download Export Templates
        if: steps.cache-templates.outputs.cache-hit != 'true'
        run: |
          GODOT_TEMPLATE_VERSION=${GODOT_VERSION/-/.}
          wget https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}/Godot_v${GODOT_VERSION}_export_templates.tpz

          mkdir -p ~/.local/share/godot/export_templates/${GODOT_TEMPLATE_VERSION}

          unzip Godot_v${GODOT_VERSION}_export_templates.tpz -d /tmp/godot_templates
          mv /tmp/godot_templates/templates/* ~/.local/share/godot/export_templates/${GODOT_TEMPLATE_VERSION}

      - name: Find Godot executable
        run: |
          GODOT_BIN=$(find . -type f -name "Godot_v${GODOT_VERSION}_linux.x86_64" | head -n1)
          chmod +x "$GODOT_BIN"
          echo "GODOT_BIN=$GODOT_BIN" >> $GITHUB_ENV
      
      - name: Create Talo cfg
        run: echo '${{ secrets.TALO_CONFIG }}' > src/addons/talo/settings.cfg

      - name: Import Project
        run: |
          "$GODOT_BIN" --headless --path src --import

      - name: Export Web
        run: |
          mkdir -p build/web

          "$GODOT_BIN" --headless --path src --export-release "Web" "$GITHUB_WORKSPACE/build/web/index.html"
      
      - name: Upload to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          ./butler push build/web MadAvidCoder/spin-phibian:web
